version: '3.4'
services:
  metad0:
    image: vesoft/nebula-metad:v2-preview-nightly
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=metad0
      - --ws_ip=metad0
      - --port=45500
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://metad0:11000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "45500:45500"
      - 11000
      - 11002
    volumes:
      - ./data/meta0:/data/meta
      - ./logs/meta0:/logs
    networks:
      - nebula-net
    restart: on-failure

  metad1:
    image: vesoft/nebula-metad:v2-preview-nightly
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=metad1
      - --ws_ip=metad1
      - --port=45500
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://metad1:11000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "45501:45500"
      - 11000
      - 11002
    volumes:
      - ./data/meta1:/data/meta
      - ./logs/meta1:/logs
    networks:
      - nebula-net
    restart: on-failure

  metad2:
    image: vesoft/nebula-metad:v2-preview-nightly
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=metad2
      - --ws_ip=metad2
      - --port=45500
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://metad2:11000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "45502:45500"
      - 11000
      - 11002
    volumes:
      - ./data/meta2:/data/meta
      - ./logs/meta2:/logs
    networks:
      - nebula-net
    restart: on-failure

  storaged0:
    image: vesoft/nebula-storaged:v2-preview-nightly
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=storaged0
      - --ws_ip=storaged0
      - --port=44500
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=2
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://storaged0:12000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "44500:44500"
      - 12000
      - 12002
    volumes:
      - ./data/storage0:/data/storage
      - ./logs/storage0:/logs
    networks:
      - nebula-net
    restart: on-failure

  storaged1:
    image: vesoft/nebula-storaged:v2-preview-nightly
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=storaged1
      - --ws_ip=storaged1
      - --port=44500
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=2
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://storaged1:12000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "44501:44500"
      - 12000
      - 12002
    volumes:
      - ./data/storage1:/data/storage
      - ./logs/storage1:/logs
    networks:
      - nebula-net
    restart: on-failure

  storaged2:
    image: vesoft/nebula-storaged:v2-preview-nightly
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --local_ip=storaged2
      - --ws_ip=storaged2
      - --port=44500
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=2
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://storaged2:12000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "44502:44500"
      - 12000
      - 12002
    volumes:
      - ./data/storage2:/data/storage
      - ./logs/storage2:/logs
    networks:
      - nebula-net
    restart: on-failure

  graphd:
    image: vesoft/nebula-graphd:v2-preview-nightly
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:45500,metad1:45500,metad2:45500
      - --port=3699
      - --ws_ip=graphd
      - --log_dir=/logs
      - --v=0
      - --minloglevel=2
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://graphd:13000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "3699:3699"
      - 13000
      - 13002
    volumes:
      - ./logs/graph:/logs
    networks:
      - nebula-net
    restart: on-failure

networks:
  nebula-net:
