services:
  metad0:
    image: docker.io/vesoft/nebula-metad:v3.8.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=metad0
      - --ws_ip=metad0
      - --port=9559
      - --ws_http_port=19559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
      - --default_parts_num=10
      - --default_replica_factor=1
      - --heartbeat_interval_secs=10
      - --agent_heartbeat_interval_secs=60
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://metad0:19559/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9559
      - 19559
      - 19560
    volumes:
      - /data/data/meta0:/data/meta
      - /data/logs/meta0:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  metad1:
    image: docker.io/vesoft/nebula-metad:v3.8.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=metad1
      - --ws_ip=metad1
      - --port=9559
      - --ws_http_port=19559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
      - --default_parts_num=10
      - --default_replica_factor=1
      - --heartbeat_interval_secs=10
      - --agent_heartbeat_interval_secs=60
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://metad1:19559/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9559
      - 19559
      - 19560
    volumes:
      - /data/data/meta1:/data/meta
      - /data/logs/meta1:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  metad2:
    image: docker.io/vesoft/nebula-metad:v3.8.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=metad2
      - --ws_ip=metad2
      - --port=9559
      - --ws_http_port=19559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
      - --default_parts_num=10
      - --default_replica_factor=1
      - --heartbeat_interval_secs=10
      - --agent_heartbeat_interval_secs=60
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://metad2:19559/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9559
      - 19559
      - 19560
    volumes:
      - /data/data/meta2:/data/meta
      - /data/logs/meta2:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  storaged0:
    image: docker.io/vesoft/nebula-storaged:v3.8.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=storaged0
      - --ws_ip=storaged0
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
      - --heartbeat_interval_secs=10
      - --raft_heartbeat_interval_secs=30
      - --raft_rpc_timeout_ms=500
      - --wal_ttl=14400
      - --disable_page_cache=false
      - --enable_rocksdb_prefix_filtering=true
      - --enable_rocksdb_whole_key_filtering=true
      # - --rocksdb_filtering_prefix_length=12
      - --enable_partitioned_index_filter=false
      - --query_concurrently=true
      - --num_io_threads=16
      - --num_max_connections=0
      - --num_worker_threads=32
      - --max_concurrent_subtasks=10
      - --memory_tracker_limit_ratio=2
      # - --rocksdb_db_options={"max_total_wal_size":"0"}
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://storaged0:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9779
      - 19779
      - 19780
    volumes:
      - /data/data/storage0:/data/storage
      - /data/logs/storage0:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  storaged1:
    image: docker.io/vesoft/nebula-storaged:v3.8.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=storaged1
      - --ws_ip=storaged1
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
      - --heartbeat_interval_secs=10
      - --raft_heartbeat_interval_secs=30
      - --raft_rpc_timeout_ms=500
      - --wal_ttl=14400
      - --disable_page_cache=false
      - --enable_rocksdb_prefix_filtering=true
      - --enable_rocksdb_whole_key_filtering=true
      # - --rocksdb_filtering_prefix_length=12
      - --enable_partitioned_index_filter=false
      - --query_concurrently=true
      - --num_io_threads=16
      - --num_max_connections=0
      - --num_worker_threads=32
      - --max_concurrent_subtasks=10
      - --memory_tracker_limit_ratio=2
      # - --rocksdb_db_options={"max_total_wal_size":"0"}
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://storaged1:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9779
      - 19779
      - 19780
    volumes:
      - /data/data/storage1:/data/storage
      - /data/logs/storage1:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  storaged2:
    image: docker.io/vesoft/nebula-storaged:v3.8.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --local_ip=storaged2
      - --ws_ip=storaged2
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
      - --heartbeat_interval_secs=10
      - --raft_heartbeat_interval_secs=30
      - --raft_rpc_timeout_ms=500
      - --wal_ttl=14400
      - --disable_page_cache=false
      - --enable_rocksdb_prefix_filtering=true
      - --enable_rocksdb_whole_key_filtering=true
      # - --rocksdb_filtering_prefix_length=12
      - --enable_partitioned_index_filter=false
      - --query_concurrently=true
      - --num_io_threads=16
      - --num_max_connections=0
      - --num_worker_threads=32
      - --max_concurrent_subtasks=10
      - --memory_tracker_limit_ratio=2
      # - --rocksdb_db_options={"max_total_wal_size":"0"}
    depends_on:
      - metad0
      - metad1
      - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://storaged2:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9779
      - 19779
      - 19780
    volumes:
      - /data/data/storage2:/data/storage
      - /data/logs/storage2:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  graphd:
    image: docker.io/vesoft/nebula-graphd:v3.8.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9669
      - --local_ip=graphd
      - --ws_ip=graphd
      - --ws_http_port=19669
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
      - --default_collate=utf8_bin
      - --accept_partial_success=false
      - --session_reclaim_interval_secs=60
      - --num_accept_threads=1
      - --num_netio_threads=0
      - --num_max_connections=0
      - --num_worker_threads=0
      - --heartbeat_interval_secs=10
      - --slow_query_threshold_us=200000
      - --enable_authorize=true
      - --auth_type=password
      - --system_memory_high_watermark_ratio=0.8
      - --enable_space_level_metrics=true
      - --enable_experimental_feature=true
      - --enable_data_balance=true
      - --memory_tracker_limit_ratio=2
      - --max_job_size=1
      - --min_batch_size=8192
      - --optimize_appendvertices=false
      - --path_batch_size=10000
      - --session_idle_timeout_secs=60
      - --client_idle_timeout_secs=60
    depends_on:
      - storaged0
      - storaged1
      - storaged2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://graphd:19669/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "9669:9669"
      - 19669
      - 19670
    volumes:
      - /data/logs/graph:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  graphd1:
    image: docker.io/vesoft/nebula-graphd:v3.8.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9669
      - --local_ip=graphd1
      - --ws_ip=graphd1
      - --ws_http_port=19669
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
      - --default_collate=utf8_bin
      - --accept_partial_success=false
      - --session_reclaim_interval_secs=60
      - --num_accept_threads=1
      - --num_netio_threads=0
      - --num_max_connections=0
      - --num_worker_threads=0
      - --heartbeat_interval_secs=10
      - --slow_query_threshold_us=200000
      - --enable_authorize=true
      - --auth_type=password
      - --system_memory_high_watermark_ratio=0.8
      - --enable_space_level_metrics=true
      - --enable_experimental_feature=true
      - --enable_data_balance=true
      - --memory_tracker_limit_ratio=2
      - --max_job_size=1
      - --min_batch_size=8192
      - --optimize_appendvertices=false
      - --path_batch_size=10000
      - --session_idle_timeout_secs=60
      - --client_idle_timeout_secs=60
    depends_on:
      - storaged0
      - storaged1
      - storaged2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://graphd1:19669/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9669
      - 19669
      - 19670
    volumes:
      - /data/logs/graph1:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  graphd2:
    image: docker.io/vesoft/nebula-graphd:v3.8.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad0:9559,metad1:9559,metad2:9559
      - --port=9669
      - --local_ip=graphd2
      - --ws_ip=graphd2
      - --ws_http_port=19669
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
      - --timezone_name=UTC+08:00
      - --default_collate=utf8_bin
      - --accept_partial_success=false
      - --session_reclaim_interval_secs=60
      - --num_accept_threads=1
      - --num_netio_threads=0
      - --num_max_connections=0
      - --num_worker_threads=0
      - --heartbeat_interval_secs=10
      - --slow_query_threshold_us=200000
      - --enable_authorize=true
      - --auth_type=password
      - --system_memory_high_watermark_ratio=0.8
      - --enable_space_level_metrics=true
      - --enable_experimental_feature=true
      - --enable_data_balance=true
      - --memory_tracker_limit_ratio=2
      - --max_job_size=1
      - --min_batch_size=8192
      - --optimize_appendvertices=false
      - --path_batch_size=10000
      - --session_idle_timeout_secs=60
      - --client_idle_timeout_secs=60
    depends_on:
      - storaged0
      - storaged1
      - storaged2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://graphd2:19669/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9669
      - 19669
      - 19670
    volumes:
      - /data/logs/graph2:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE
  
  console:
    image: docker.io/vesoft/nebula-console:v3.6.0
    entrypoint: ""
    command: 
      - sh
      - -c
      - |
        for i in `seq 1 60`;do
          var=`nebula-console -addr graphd -port 9669 -u root -p nebula -e 'ADD HOSTS "storaged0":9779,"storaged1":9779,"storaged2":9779'`;
          if [[ $$? == 0 ]];then
            break;
          fi;
          sleep 1;
          echo "retry to add hosts.";
        done && tail -f /dev/null;

    depends_on:
      - graphd
    networks:
      - nebula-net

  spark-master:
    image: my-spark-app-image
    user: "1001:1001"
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark/apps:/opt/bitnami/spark/apps
      - ./spark/data:/opt/bitnami/spark/data
      - ./spark/config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - nebula-net

  spark-worker:
    image: my-spark-app-image
    user: "1001:1001"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./spark/apps:/opt/bitnami/spark/apps
      - ./spark/data:/opt/bitnami/spark/data
      - ./spark/config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - nebula-net

networks:
  nebula-net:
