global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'triton'
    static_configs:
      - targets: ['triton-server:8002']

  - job_name: 'nebula-stats-exporter'
    static_configs:
      - targets: ['nebula-stats-exporter:9100']

  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra:7070']
