{
 "title": "Triton Server",
 "description": "Visualize metrics from the Triton server.",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "nv_gpu_utilization" } }
  ]
 },
 "panels": [
  {
   "title": "Request success / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_request_success{job=\"$job\"}[30s]))",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Inference time / req",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(nv_inference_compute_infer_duration_us{job=\"$job\"}[30s]) / irate(nv_inference_request_success{job=\"$job\"}[30s])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Request fail / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_request_failure{job=\"$job\"}[5m]) )",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(nv_inference_request_duration_us{job=\"$job\"}[30s]) / irate(nv_inference_request_success{job=\"$job\"}[30s])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "GPU Util",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nv_gpu_utilization{job=\"$job\"}",
     "legendFormat": "Util"
    }
   ]
  },
  {
   "title": "DB ratio ( #request / #exec )",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_request_success{job=\"$job\"}[30s])/rate(nv_inference_exec_count{job=\"$job\"}[30s]) )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nv_gpu_power_usage{job=\"$job\"})",
     "legendFormat": "Total Power (W)"
    }
   ]
  },
  {
   "title": "Batchsize ( #infer/ #exec)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_count{job=\"$job\"}[30s])/rate(nv_inference_exec_count{job=\"$job\"}[30s]) )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Queue time / req",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (model,version) (irate(nv_inference_queue_duration_us{job=\"$job\"}[30s])  / irate(nv_inference_request_success{job=\"$job\"}[30s]))",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Input time / req",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(nv_inference_compute_input_duration_us{job=\"$job\"}[30s]) / irate(nv_inference_request_success{job=\"$job\"}[30s])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Output time / req",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(nv_inference_compute_output_duration_us{job=\"$job\"}[30s]) / irate(nv_inference_request_success{job=\"$job\"}[30s])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  }
 ]
}